Update to fix error with new TextCurve structure
Line 450 crv.align will no longer work. Needs update from align to align_x. This fixes an error (AttributeError:  'TextCurve' object has no attribute 'align') with v 2.79 of Blender.